name: "Test"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'latest'
      - 'ci*' # Allow testing CI fixes without opening a PR

jobs:
  tests:
    strategy:
      # Allow other jobs to finish building and cache properly before bailing
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: sourmash-bio
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: flake checks
      run: nix flake check --keep-going --print-build-logs

