name: "Test"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'latest'
      - 'ci*' # Allow testing CI fixes without opening a PR

jobs:
  tests:
    strategy:
      # Allow other jobs to finish building and cache properly before bailing
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            # Latest and greatest release of Nix
            install_url: https://nixos.org/nix/install

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        install_url: ${{ matrix.install_url }}
    - uses: cachix/cachix-action@v12
      with:
        name: sourmash-bio
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: flake checks
      run: nix flake check --keep-going --print-build-logs

